### ISSUE TITLE
Error: File System Not Supported

### ISSUE THREAD

**Issue by mczero80** [Rion96/GKey#2]
Hello,

I tried to mount/use the GKey.iso, but TempleOS corresponds with a File System Not Supported error. 
Or is there another method for transfering these files from the host system (I use VirtualBox) to TempleOS?

**Comment by MineKnad** [comment]
Same problem here! Really is a shame, that it hasn't been fixed yet

**Comment by Rion96** [comment]
Sorry for taking so incredibly long with my response. It's been a long time since I've worked on this and I had to relearn a lot. Indeed the final releases of TempleOS broke ISO compatibility with older releases. It's incredibly tedious to make new ISOs that are compatible, but I think I managed to create one for GKey that should work. You can find it [here](https://github.com/Rion96/GKey/releases/tag/v3.0).

In case it doesn't work for you, another option is always to use one of the older TempleOS builds. They are available [here](https://archive.org/download/TerryADavis_TempleOS_Archive/software/TempleOS/). A slightly older build of V5.03 should probably do the trick, but if you want to play it safe V5.02 should definitely work.
